version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: build/local.Dockerfile
            args:
                NODE_MAJOR: 20
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            APACHE_DOCUMENT_ROOT: '/var/www/html/public'
            PHP_DATE_TIMEZONE: 'Europe/Rome'
            PHP_POOL_NAME: "laravel_php"
            SSL_MODE: off
            WEBUSER_HOME: '/var/www/html'
        volumes:
            - '../:/var/www/html'
        networks:
            - weroad_assessment
        depends_on:
            - mariadb
            - mailpit

    phpmyadmin:
        container_name: weroad_assessment_db_viewer
        depends_on:
            - mariadb
        image: phpmyadmin/phpmyadmin
        volumes:
            - ./phpMyAdmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php
            - ./phpMyAdmin/themes/blueberry:/var/www/html/themes/blueberry
        ports:
            - "8081:80"
        environment:
            PMA_HOST: mariadb
            MYSQL_ROOT_PASSWORD: ''
        networks:
            - weroad_assessment

    cron:
        image: serversideup/php:8.2-cli
        command: [ "su", "webuser", "-c", "cd /var/www/html && php artisan schedule:work" ]
        environment:
            PHP_POOL_NAME: "laravel_cron"
        volumes:
            - '../:/var/www/html'
        restart: always
        networks:
            - weroad_assessment
        depends_on:
            - mariadb

    mariadb:
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
            MYSQL_ROOT_PASSWORD: ''
        volumes:
            - './database/mariadb/volume:/var/lib/mysql'
            - './database/mariadb/scripts/create-application-database.sh:/docker-entrypoint-initdb.d/10-create-application-database.sh'
        restart: always
        networks:
            - weroad_assessment
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p""'
            retries: 3
            timeout: 5s

    mailpit:
        container_name: weroad_assessment_mailer
        image: 'axllent/mailpit:latest'
        env_file:
            - ../.env
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - weroad_assessment

networks:
    weroad_assessment:
        driver: bridge
